// The following registers definition are refer to STM32F746G
#define FLASH_AXIM_BASE			(0x08000000UL)
#define PERIPH_BASE				(0x40000000UL)

#define APB1PERIPH_BASE			(PERIPH_BASE + 0x00000000UL)
#define APB2PERIPH_BASE			(PERIPH_BASE + 0x00010000UL)
#define AHB1PERIPH_BASE			(PERIPH_BASE + 0x00020000UL)
#define AHB2PERIPH_BASE			(PERIPH_BASE + 0x10000000UL)
#define AHB3PERIPH_BASE			(PERIPH_BASE + 0x20000000UL) // External memory

#define GPIOI_BASE				(AHB1PERIPH_BASE + 0x2000UL)
#define RCC_BASE				(AHB1PERIPH_BASE + 0x3800UL)
#define FLASH_BASE				(AHB1PERIPH_BASE + 0x3C00UL)
#define PWR_BASE				(APB1PERIPH_BASE + 0x7000UL)
#define USART1_BASE				(APB2PERIPH_BASE + 0x1000UL)

// Flash register definition
#define FLASH_ACR				(FLASH_BASE + 0x00UL)

// Flash register definition
#define PWR_CR1					(PWR_BASE + 0x00UL)
#define PWR_CSR1				(PWR_BASE + 0x04UL)
#define PWR_CR2					(PWR_BASE + 0x08UL)
#define PWR_CSR2				(PWR_BASE + 0x0CUL)

// RCC(Reset Clock Control) register definition
#define RCC_CR					(RCC_BASE + 0x00UL)
#define RCC_PLLCFGR				(RCC_BASE + 0x04UL)
#define RCC_CFGR				(RCC_BASE + 0x08UL)
#define RCC_CIR					(RCC_BASE + 0x0CUL)
#define RCC_AHB1RSTR			(RCC_BASE + 0x10UL)
#define RCC_AHB2RSTR			(RCC_BASE + 0x14UL)
#define RCC_AHB3RSTR			(RCC_BASE + 0x18UL)
#define RCC_APB1RSTR			(RCC_BASE + 0x20UL)
#define RCC_APB2RSTR			(RCC_BASE + 0x24UL)
#define RCC_AHB1ENR				(RCC_BASE + 0x30UL)
#define RCC_AHB2ENR				(RCC_BASE + 0x34UL)
#define RCC_AHB3ENR				(RCC_BASE + 0x38UL)
#define RCC_APB1ENR				(RCC_BASE + 0x40UL)
#define RCC_APB2ENR				(RCC_BASE + 0x44UL)
#define RCC_BDCR				(RCC_BASE + 0x70UL)
#define RCC_CSR					(RCC_BASE + 0x74UL)
#define RCC_SSCGR				(RCC_BASE + 0x80UL)
#define RCC_PLLI2SC_FGR			(RCC_BASE + 0x84UL)
#define RCC_PLLSAI_CFGR			(RCC_BASE + 0x88UL)
#define RCC_DCKCF_GR1 			(RCC_BASE + 0x8CUL)
#define RCC_DCKCF_GR2 			(RCC_BASE + 0x90UL)

// GPIOI register definition
#define GPIOI_MODER_ADDR		(GPIOI_BASE + 0x00UL)
#define GPIOI_OTYPER_ADDR		(GPIOI_BASE + 0x04UL)
#define GPIOI_OSPEEDR_ADDR		(GPIOI_BASE + 0x08UL)
#define GPIOI_PUPDR_ADDR		(GPIOI_BASE + 0x0CUL)
#define GPIOI_IDR_ADDR			(GPIOI_BASE + 0x10UL)
#define GPIOI_ODR_ADDR			(GPIOI_BASE + 0x14UL)
#define GPIOI_BSRR_ADDR			(GPIOI_BASE + 0x18UL)
#define GPIOI_LCKR_ADDR			(GPIOI_BASE + 0x1CUL)
#define GPIOI_AFRL_ADDR			(GPIOI_BASE + 0x20UL)
#define GPIOI_AFRH_ADDR			(GPIOI_BASE + 0x24UL)
