// The following registers definition are refer to STM32F746G
#define FLASH_AXIM_BASE			(0x08000000UL)
#define PERIPH_BASE				(0x40000000UL)

#define APB1PERIPH_BASE			(PERIPH_BASE + 0x00000000UL)
#define APB2PERIPH_BASE			(PERIPH_BASE + 0x00010000UL)
#define AHB1PERIPH_BASE			(PERIPH_BASE + 0x00020000UL)
#define AHB2PERIPH_BASE			(PERIPH_BASE + 0x10000000UL)
#define AHB3PERIPH_BASE			(PERIPH_BASE + 0x20000000UL) // External memory

// RCC(Reset Clock Control) register definition
#define RCC_BASE				(AHB1PERIPH_BASE + 0x3800UL)
#define RCC_CR					((uint32_t*)(RCC_BASE + 0x00))
#define RCC_PLLCFGR				((uint32_t*)(RCC_BASE + 0x04))
#define RCC_CFGR				((uint32_t*)(RCC_BASE + 0x08))
#define RCC_CIR					((uint32_t*)(RCC_BASE + 0x0C))
#define RCC_AHB1RSTR			((uint32_t*)(RCC_BASE + 0x10))
#define RCC_AHB2RSTR			((uint32_t*)(RCC_BASE + 0x14))
#define RCC_AHB3RSTR			((uint32_t*)(RCC_BASE + 0x18))
#define RCC_APB1RSTR			((uint32_t*)(RCC_BASE + 0x20))
#define RCC_APB2RSTR			((uint32_t*)(RCC_BASE + 0x24))
#define RCC_AHB1ENR				((uint32_t*)(RCC_BASE + 0x30))
#define RCC_AHB2ENR				((uint32_t*)(RCC_BASE + 0x34))
#define RCC_AHB3ENR				((uint32_t*)(RCC_BASE + 0x38))
#define RCC_APB1ENR				((uint32_t*)(RCC_BASE + 0x40))
#define RCC_APB2ENR				((uint32_t*)(RCC_BASE + 0x44))
#define RCC_BDCR				((uint32_t*)(RCC_BASE + 0x70))
#define RCC_CSR					((uint32_t*)(RCC_BASE + 0x74))
#define RCC_SSCGR				((uint32_t*)(RCC_BASE + 0x80))
#define RCC_PLLI2SC_FGR			((uint32_t*)(RCC_BASE + 0x84))
#define RCC_PLLSAI_CFGR			((uint32_t*)(RCC_BASE + 0x88))
#define RCC_DCKCF_GR1 			((uint32_t*)(RCC_BASE + 0x8C))
#define RCC_DCKCF_GR2 			((uint32_t*)(RCC_BASE + 0x90))

// Peripheral register definition
// GPIO register definition
#define GPIOI_BASE				(PERIPH_BASE + 0x22000UL)
#define GPIOI_MODER				((uint32_t*)(GPIOI_BASE + 0x00))
#define GPIOI_OTYPER			((uint32_t*)(GPIOI_BASE + 0x04))
#define GPIOI_OSPEEDR			((uint32_t*)(GPIOI_BASE + 0x08))
#define GPIOI_PUPDR				((uint32_t*)(GPIOI_BASE + 0x0C))
#define GPIOI_IDR				((uint32_t*)(GPIOI_BASE + 0x10))
#define GPIOI_ODR				((uint32_t*)(GPIOI_BASE + 0x14))
#define GPIOI_BSRR				((uint32_t*)(GPIOI_BASE + 0x18))
#define GPIOI_LCKR				((uint32_t*)(GPIOI_BASE + 0x1C))
#define GPIOI_AFRL				((uint32_t*)(GPIOI_BASE + 0x20))
#define GPIOI_AFRH				((uint32_t*)(GPIOI_BASE + 0x24))

#define GPIOI_MODER_IN			(0x0)
#define GPIOI_MODER_OUT			(0x1)
#define GPIOI_MODER_MULTI		(0x2)
#define GPIOI_MODER_SIM			(0x3)
#define GPIOI_OTYPER_PUSH_PULL	(0x0)
#define GPIOI_OTYPER_OPEN_DRAIN	(0x1)
#define GPIOI_OSPEEDR_LOW		(0x0)
#define GPIOI_OSPEEDR_MID		(0x1)
#define GPIOI_OSPEEDR_HIGH		(0x2)
#define GPIOI_OSPEEDR_FULL		(0x3)
#define GPIOI_PUPDR_NONE		(0x0)
#define GPIOI_PUPDR_PULL_UP		(0x1)
#define GPIOI_PUPDR_PULL_DOWN	(0x2)
#define GPIOI_PUPDR_RESERVE		(0x3)
